#!/bin/sh

echo "
===============
|  Running kotlinter check......
===============
"

if ! ./gradlew lintKotlin ; then
    printf 1>&2 "\nlintKotlin found problems, running formatKotlin; commit the result and re-push"
    $GRADLEW formatKotlin
    exit 1
fi
